# Generated by Django 5.0.1 on 2024-01-24 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddContent',
            fields=[
                ('content_id', models.AutoField(primary_key=True, serialize=False)),
                ('U_ID', models.IntegerField(null=True)),
                ('content_name', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_addcontent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
